### PR TITLE
Tag search

### PR DESCRIPTION
**Pull request by berlintam**

### CODE REVIEW

**Comment by berlintam** [comment]
@Powerglove I had another thought about this as I was biking to work - it would be cool if you could pull the new checkbox form into a partial so that it can be shared on other pages potentially, for example on the individual user page that Dayana is working on. You can put it in a folder called 'shared' or something... and then you would pass in the path we're sending the GET request to as a local variable. 

make sense?

**Comment by langjoh** [comment]
bildschirmfoto 2016-09-19 um 15 33 40

**Comment by langjoh** [comment]
@berlintam Two questions:
1. the check box doesn't stay checked after reloading the page. How can I change this? 
2. Travis tells me that my branch has conflicts that should be resolved. What should I do about this? 
Thanks a lot :)

**Comment by berlintam** [comment]
1. not sure, I'll have to think about it. 
2. I may have messed things up when i made this PR, perhaps @carpodaster can shed some light on the best way to do this. I would suggest 
   a) wait until the tagging branch is merged, this branch should then re-orientate itself to master & hopefully not have any merge conflicts. Or maybe you'll have to merge master into this branch once the tagging branch is merged.
   b) close this PR & make a new one where you say you want to merge this branch INTO the tagging branch (instead of into the master branch). Then we can merge this brach into taggings & merge all of it into master together. 

Does any of that make sense?

**Comment by langjoh** [comment]
@berlintam Issue 1 (check box choice persists) is solved. 
And i will ask @carpodaster about the merge conflict tomorrow.

**Comment by berlintam** [comment]
ok, so my thought that this branch would be fixed once we merged tagging was wrong. sorry!!!! I lead you astray. 
Best to ask Carsten about what to do now. It'll be a fun lesson in git messes :)

**Comment by berlintam** [comment]
@Powerglove I think if you just merge master into this branch & fix the conflict in the index.html, things'll be ok. Let me know if you want me to do it and I totally can, & then i'll merge it.

**Comment by berlintam** [comment]
super

**Pull request merged**
