### PR TITLE
Add rack-cors Gem and implement CORS to allow whitelisted Origins to …

### PR DESCRIPTION
**Pull request by aydamacink**
…make HTTP requests.

### CODE REVIEW

**Comment by berlintam** [comment]
@starkcoffee any chance u can take a quick look at this? You're the api queen :)

**Comment by starkcoffee** [comment]
+1 Thx!

**Comment by starkcoffee** [comment]
Actually is it necessary to whitelist sounddrop.audio? As our code will already be running under that domain? And the codepen.io api is not really needed as it isn't a general purpose api?

**Comment by berlintam** [comment]
@starkcoffee they want to implement this b/c because they want to "make a black form in which a user or developer could type the api endpoint to see what she/he will get to make it easier to write the documentation and for us to understand how the api works"

They were using codepen to built it faster, and once it's done they can erase the codepen permissions.

**Comment by aydamacink** [comment]
@starkcoffee : Joe said that in one of his jobs he did this, because their own js couldn't access the requests.... so that is the reason and we could delete copen afterwards its only too build this sort of developer tool where you can see what each endpoint  will return and for us to write the documentation :)

**Comment by berlintam** [comment]
ok, @starkcoffee and I chatted about it & it's cool. document away!

**Pull request merged**
