### PR TITLE
add map marker

### PR DESCRIPTION
**Pull request by berlintam**
I changed the iframe a bit so that we display the address & map marker on the map. 

But it doesn't seem possible to change the map markers themselves in the iframe. So either we need to kick out the iframe & do something like this: https://developers.google.com/maps/documentation/javascript/examples/marker-symbol-custom or we just have to be happy how it is. 

Also, we don't need the coordinates for the google map. Google is smart enough to figure everything out based on the address. Is there any reason we need the coordinates then? If not, we should chuck 'em. 

what are thoughts about this? @starkcoffee @nynnejc @WlFranzi

### CODE REVIEW

**Comment by berlintam** [comment]
btw, I figured this out using this tutorial: https://developers.google.com/maps/documentation/embed/guide#view_mode

**Comment by berlintam** [comment]
woot!
screen shot 2016-04-11 at 19 54 09

**Comment by berlintam** [comment]
closes https://github.com/sounddrop/sounddrop/issues/46

**Comment by starkcoffee** [comment]
yay! oh one thing: we should put our google api key in an environment variable.

**Comment by starkcoffee** [comment]
But this is fine to merge, let's just figure out how to store it not in github and then change over they key.

**Comment by nynnejc** [comment]
🌟✨💫💞

**Pull request merged**
