### PR TITLE
Update to Rails v4.7.2.1

### PR DESCRIPTION
**Pull request by carpodaster**

### CODE REVIEW

**Comment by carpodaster** [comment]
Specs failing for reasons described in in #106

**Comment by carpodaster** [comment]
I've rebased this PR against the current master. Specs are passing now.

**Comment by berlintam** [comment]
@carpodaster is this good to merge? Should we expect anything strange to happen?

**Comment by carpodaster** [comment]
@berlintam this should be good to merge w/o any expected hiccups

**Comment by berlintam** [comment]
thanks

**Pull request merged**
