### PR TITLE
Style drop#new page

### PR DESCRIPTION
**Pull request by berlintam**
looks like this now! I made use of the bootstrap classes if  @nynnejc  & @WlFranzi wanna take a look at that. Also, I made the form a bit clearer, so now a user knows what's required when submitting a drop. Lemmie know what you think!

screen shot 2015-10-12 at 20 57 38

### CODE REVIEW

**Comment by berlintam** [comment]
I changed the text to 'First: _choose_ your sound'

**Comment by berlintam** [comment]
Anyone have any thoughts on this? If not I'll just merge.... @WlFranzi @starkcoffee @nynnejc

**Comment by nynnejc** [comment]
I think it looks good!

**Comment by starkcoffee** [comment]
Yeh looks swish! Great! An idea to make the labels a bit shorter: we could put a little orange asterisk near the label rather than the word (required)?

**Comment by berlintam** [comment]
now it looks like this, I used the bootstrap glyphicons for the required icons. Let me know what you think!

Also, it occurred to me that we are not making use of the bootstrap form class, which can really make forms look a lot better. http://getbootstrap.com/css/#forms If someone's looking to explore bootstrap & play around w/ styling, this could be a good place to start!

screen shot 2015-10-23 at 07 59 30

**Comment by berlintam** [comment]
hmmmm tests are failing in a really weird way now....

**Comment by starkcoffee** [comment]
This looks great! Good point about bootstrap forms.

**Pull request merged**
