### PR TITLE
Add contributor covenant Code of Conduct

### PR DESCRIPTION
**Pull request by carpodaster**

### CODE REVIEW

**Comment by berlintam** [comment]
yaaaa! thanks @carpodaster! Weird that this is failing thou... maybe we have some randomly failing specs :(

**Comment by carpodaster** [comment]
@berlintam oops, didn't realise it was failing. It shouldn't, since it's only markdown :)  Looking at the Travis CI build, it says `Google Geocoding API error: over query limit.`, indicating that `Geocoder` is making actual web requests during tests. We have learnt only recently that apparently VCR punches a hole through `WebMock.disable_net_connect`.

I understand @aydamacink and @Powerglove have already started working on preventing Geocoder from doing live requests and use test mocks instead.

**Comment by aydamacink** [comment]
hi we did this already, but it is within a branch that still needs to be merged, but before that, we still need to fix a few things

**Comment by berlintam** [comment]
@carpodaster broken specs should now be fixed in master - so this branch is good to go :)

**Comment by carpodaster** [comment]
Specs are not failing anymore.

**Comment by berlintam** [comment]
thanks!

**Pull request merged**
